-- highlight settings
vim.g.go_auto_sameids = 0
vim.g.go_highlight_types = 1
vim.g.go_highlight_fields = 1
vim.g.go_highlight_functions = 1
vim.g.go_highlight_function_calls = 1
vim.g.go_highlight_functions = 1
vim.g.go_fillstruct_mode = 'gopls'
vim.g.go_def_mapping_enabled = 0
